.\" texinfo(5)
.\" Copyright (C) 1998, 1999, 2002 Free Software Foundation, Inc.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that this permission notice may be stated in a
.\" translation approved by the Foundation.
.\"
.TH TEXINFO 5 "GNU Texinfo" "FSF"
.SH NAME
texinfo \- 软件文档系统
.SH "DESCRIPTION 描述"
Texinfo 是一种文档系统，使用单一的源文件来产生在线文档以及可打印的输出。它主要用于书写软件使用手册。
.PP
要查看 Texinfo 语言和相关工具的全面描述，请查看 Texinfo 手册(以 Texinfo 自身写成)。最简单的，从 shell 中运行这个命令：
.RS
.I info texinfo
.RE
或者在 Emacs 中输入按键序列：
.RS
.I M-x info RET m texinfo RET
.RE
也可以把你带到那里。
.SH "AVAILABILITY 下载"
ftp://ftp.gnu.org/pub/gnu/texinfo-<version>.tar.gz
.br
或者任何 GNU 镜像站。
.SH "REPORTING BUGS 报告错误"
将错误报告发送到 bug-texinfo@gnu.org，一般的问题和讨论则发送到 help-texinfo@gnu.org。
.SH "SEE ALSO 参见"
info(1), install-info(1), makeinfo(1), texi2dvi(1), texindex(1).
.br
emacs(1), tex(1).
.br
info(5).
