.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH DMESG 8 
.SH NAME
dmesg \- print or control the kernel ring buffer
.SH 总览
.BI "dmesg [ \-c ] [ \-n " 级别 " ] [ \-s " 缓冲区大小 " ]"
.SH 描述
.B dmesg
用于检测和控制内核环缓冲。

程序用来帮助用户了解系统的启动信息。用户只需使用命令：
.RS
dmesg > boot.messages
.RE
然后将文件
.I boot.messages
邮寄给某些可以帮你调试系统的人。而无须手工拷贝系统启动信息。
.SH 选项
.TP
.B \-c
当完成打印显示后清除环缓冲内的内容。
.TP
.BI \-s 缓冲区大小
定义一个大小为"缓冲区大小"的缓冲区用于查询内核环缓冲区。
默认大小为 8196（此大小与 2.0.33 和 2.1.103 内核的默认
syslog 缓冲区大小一致），
如果你设置了一个大于默认值的环缓冲区，
那你就可以用这个选项定义一个相当的缓冲区
来查看完整的环缓冲区内容。
.TP
.BI \-n 级别
设置
.I 级别
为记录控制台启动信息的级别。比如，
.B \-n 1
指的就是将此级别设为最低级，
除了内核恐慌信息之外不会向控制台显示信息。
所有级别的启动信息还将记录到
.IR /proc/kmsg ,
文件中，因此，
.BR syslogd (8)
同样可以用来对信息的输出进行控制。当使用
.B \-n
选项时，
.B dmesg
将
.I 不会 
清除内核环缓冲区中的内容。
当同时使用以上两个选项时，只有最后一个选项才会产生效果。
.SH 又见
.BR syslogd (8)
.SH 作者
Theodore Ts'o (tytso@athena.mit.edu)

.SH "[中文版维护人]"
.B 所罗门 <solomen@email.com.cn>
.SH "[中文版最新更新]"
2001/04/01
.SH "[中国 Linux 论坛 man 手册页翻译计划]"
.BI http://cmpp.linuxforum.net
