.TH IPTABLES-RESTORE 8 "Jan 04, 2001" "" ""
.\"
.\" Man page written by Harald Welte <laforge@gnumonks.org>
.\" It is based on the iptables man page.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAME
iptables-restore \- 恢复 IP Tables
.SH "总览 SYNOPSIS"
.BR "iptables-restore " "[-c] [-n]"
.br
.SH "描述 DESCRIPTION"
.PP
.B iptables-restore
用来从 STDIN 给出的数据中恢复 IP Tables。
使用 shell 的 I/O 重定向功能来从文件中获取数据
.TP
\fB\-c\fR, \fB\-\-counters\fR
恢复所有报文和字节计数的值
.TP
\fB\-n\fR, \fB\-\-noflush\fR 
.TP
不刷新表中从前的内容。如果没有指定，
.B iptables-restore
会刷新 (删除) 相应 IP Tables 中所有从前的内容
.SH BUGS
无
.SH "作者 AUTHOR"
Harald Welte <laforge@gnumonks.org>
.SH "参见 SEE ALSO"
.BR iptables-save "(8), " iptables "(8) "
.PP
iptables-HOWTO 记述了 iptables 用法的细节，
NAT-HOWTO 记述了 NAT 的细节，
netfilter-hacking-HOWTO 记述了内部实现的细节
.
.SH "[中文版维护人]"
.B 杨鹏 NetSnake <email>
.br
.B Poopy <email> (?)
.SH "[中文版最新更新]"
.B 2002.05.01
.SH "《中国linux论坛man手册翻译计划》:"
.BI http://cmpp.linuxforum.net 
