.TH QUOTASTATS 8 "1999年8月20日星期五"
.UC 4
.SH NAME(名称)
quotastats - 显示与配额子系统相关的统计信息
.SH SYNOPSIS(总览)
.B quotastats
.SH DESCRIPTION(描述)
该命令显示与配额子系统相关的统计信息.
.SH "SEE ALSO"(另见)
quota(1), quotactl(2)
.SH AUTHOR(作者)
Marco van Wieringen \<mvw@planets.elm.net\>
.br
Jan Kara \<jack@atrey.karlin.mff.cuni.cz\>
.br
作了细小的修改.


.SH "[中文版维护人]"
.B riser <boomer@ccidnet.com>
.SH "[中文版最新更新]"
2001/7/10
.SH "[中国 Linux 论坛 man 手册页翻译计划]"
.BI http://cmpp.linuxforum.net
