.TH CONVERTQUOTA 8 "Fri Aug 20 1999"
.UC 4
.SH NAME
convertquota \- convert quota from old file format to new one
.SH SYNOPSIS
.B convertquota
[
.B -ug
] [
.B -e
|
.B -f
]
.I filesystem
.SH DESCRIPTION
.B convertquota
converts old quota files
.BR quota.user
and
.BR quota.group
to files
.BR aquota.user
and
.BR aquota.group
in new format currently used by 2.4.0-ac? and newer or by Red Hat Linux 2.4 kernels on
.IR filesystem .
.PP
New file format allows using quotas for 32-bit uids / gids, setting quotas for root,
accounting used space in bytes (and so allowing use of quotas in ReiserFS) and it
is also architecture independent. This format introduces Radix Tree (a simple form of tree
structure) to quota file.
.SH OPTIONS
.TP
.B -u
convert user quota file. This is the default.
.TP
.B -g
convert group quota file.
.TP
.B -f
convert from old file format to new one. This is the default.
.TP
.B -e
convert new file format from big endian to little endian.
.TP
.B -V
print version information.
.SH FILES
.TP 20
.B aquota.user
new user quota file
.TP
.B aquota.group
new group quota file
.SH "SEE ALSO"
.BR quota (1),
.BR setquota (8),
.BR edquota (8),
.BR quotacheck (8),
.BR quotaon (8),
.BR repquota (8)
.SH AUTHOR
Jan Kara \<jack@suse.cz\>

