.\"
.\" Generated automatically from apropos.1.in by the
.\" configure script.
.\"
.\" Man page for apropos
.\"
.\" Copyright (c) 1990, 1991, John W. Eaton.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.  
.\"
.\" John W. Eaton
.\" jwe@che.utexas.edu
.\" Department of Chemical Engineering
.\" The University of Texas at Austin
.\" Austin, Texas  78712
.\"
.TH apropos 1 "Jan 15, 1991"
.SH NAME
apropos \- 在 whatis 数据库中查找字符串
.SH "总览 (SYNOPSIS)"
.BI apropos
keyword ...
.SH "描述 (DESCRIPTION)"
apropos 命令在一些特定的包含系统命令的简短描述的数据库文件里查找关键字， 然后把
结果送到标准输出。 
.SH "参见 (SEE ALSO)"
whatis(1), man(1).
.SH "[中文版维护人]"
.B 唐友 <tony_ty@263.net>
.SH "[中文版最新更新]"
.BR 2001/9/20
.SH "[中国Linux论坛man手册页翻译计划]"
.BI http://cmpp.linuxforum.net
