.TH BASENAME "1" "August 1999" "GNU sh-utils 2.0" FSF
.SH NAME
basename \- 从文件名中剥离目录和后缀
.SH "总览 (SYNOPSIS)"
.B basename
\fINAME \fR[\fISUFFIX\fR]
.br
.B basename
\fIOPTION\fR
.SH "描述 (DESCRIPTION)"
.PP
.\" Add any additional description here
.PP
显示 去掉 目录成分 后的 NAME. 如果 指定了 SUFFIX, 就 同时 去掉
拖尾的 SUFFIX.
.TP
\fB\-\-help\fR
显示 帮助信息, 然后 结束
.TP
\fB\-\-version\fR
显示 版本信息, 然后 结束
.SH "报告 BUGS"
发现的 bug 送往 <bug-sh-utils@gnu.org>.
.SH "另见 (SEE ALSO)"
.B basename
的 完整文档 以 Texinfo 手册 的 格式 维护. 如果 正确 安装了
.B info
和
.B basename
程序, 使用 命令
.IP
.B info basename
.PP
能够 访问到 完整 的 手册.

.SH "版权 (COPYRIGHT)"
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "[中文版维护人]"
.B 徐明 <xuming@iname.com>
.SH "[中文版最新更新]"
.BR 2001/12/10
第一版
.SH "《中国Linux论坛man手册页翻译计划》："
.BI http://cmpp.linuxforum.net
