.TH CKSUM 1 "1999年12月" "GNU textutils 2.0a" 
.SH NAME(名称)
cksum \- 一个文件的检查和以及字节数
.SH SYNOPSIS(总览)
.B ../src/cksum
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION(描述)
.\" 在这儿添加任何附加的描述信息
.PP
输出CRC(循环冗余校验码)检查和以及每个FILE的字节数.
.TP
\fB\-\-help\fR
显示帮助并退出
.TP
\fB\-\-version\fR
输出版本信息并退出
.SH AUTHOR(作者)
Q. Frank Xia.
.SH "REPORTING BUGS"(报告BUGS)
报告bugs,请发到<bug-textutils@gnu.org>.
.SH COPYRIGHT(版权)
Copyright \(co 1999 Free Software Foundation, Inc.
.br
这是自由软件;参看复制条件的源文件.不承担任何责任;更不用说商业性或针对特定目的的适用性.
.SH "SEE ALSO"(另见)
.B cksum
的完整文档是以Texinfo手册的方式维护的.如果你正确地安装了
.B info
和
.B cksum
程序,那么使用命令
.IP
.B info cksum
.PP
应该会让你访问到整个手册.

.SH "[中文版维护人]"
.B riser <boomer@ccidnet.com>
.SH "[中文版最新更新]"
.BR 2001/08/08
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
