.TH DIRNAME "1" "1999年8月" "GNU sh-utils 2.0" FSF
.SH NAME(名称)
dirname \- 从文件名剥离非目录的后缀
.SH SYNOPSIS(总览)
.B dirname
\fINAME\fR
.br
.B dirname
\fIOPTION\fR
.SH DESCRIPTION(描述)
.PP
.\" 在这儿添加任何附加的描述
.PP
打印去除了/后面部分的NAME;如果NAME没有包含/,则输出`.'(表示当前目录).
.TP
\fB\-\-help\fR
显示帮助并退出
.TP
\fB\-\-version\fR
输出版本信息并退出
.SH "REPORTING BUGS"(报告BUGS)
报告bugs请发到<bug-sh-utils@gnu.org>.
.SH "SEE ALSO"(另见)
.B dirname
的完整文档是以Texinfo手册的形式维护的.如果
你正确地安装了
.B info
和
.B dirname
程序,那么命令
.IP
.B info dirname
.PP
应该可以让你访问到整个手册.
.SH COPYRIGHT
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "[中文版维护人]"
.B riser <boomer@ccidnet.com>
.SH "[中文版最新更新]"
.BR 2001/08/08
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
