.TH FALSE "1" "August 1999" "GNU sh-utils 2.0" FSF
.SH NAME
false \- (失败的)什么都不做
.SH "总览 (SYNOPSIS)"
.B false
[\fI忽略命令行参数\fR]
.br
.B false
\fIOPTION\fR
.SH "描述 (DESCRIPTION)"
.PP
.\" Add any additional description here
.PP
程序 结束 时, 产生 表示 失败 的 状态码.
.PP
下列的 选项 没有 简写 形式.
.TP
\fB\-\-help\fR
显示 帮助信息, 然后 退出.
.TP
\fB\-\-version\fR
显示 版本信息, 然后 退出.
.SH "报告 BUGS"
发现 的 错误 送往 <bug-sh-utils@gnu.org>.
.SH "另见 (SEE ALSO)"
.B false
的 完整 文档 以 Texinfo 手册 形式 维护. 如果 正确 安装 了
.B info
和
.B false
程序, 用 命令
.IP
.B info false
.PP
能够 访问到 完整 的 手册.

.SH "版权 (COPYRIGHT)"
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "[中文版维护人]"
.B 徐明 <xuming@iname.com>
.SH "[中文版最新更新]"
.BR 2001/12/17
第一版
.SH "《中国Linux论坛man手册页翻译计划》："
.BI http://cmpp.linuxforum.net
