
.TH HOSTID "1" "1999年8月" "GNU sh-utils 2.0" FSF


.SH NAME(名称)


hostid \- 显示当前主机的数字化标识


.SH SYNOPSIS(总览)


.B hostid


[\fI-v\fR]


.SH DESCRIPTION(描述)


.PP


.\" Add any additional description here


.PP


显示当前主机的数字化标识(以十六进制的形式表示).


.TP


\fB\-\-help\fR


显示帮助信息后退出


.TP


\fB\-\-version\fR


输出版本信息后退出


.SH "REPORTING BUGS"(报告BUGS)


报告bugs,请发送到<bug-sh-utils@gnu.org>.


.SH "SEE ALSO"(另见)


完整的


.B hostid


文档是以Texinfo手册形式维护的.如果在你那儿安装好了


.B info


和


.B hostid


程序,那么命令


.IP


.B info hostid


.PP


会让你访问到整个手册.


.SH COPYRIGHT(版权)


Copyright \(co 1999 Free Software Foundation, Inc.


.br


This is free software; see the source for copying conditions.  There is NO


warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "[中文版维护人]"
.B riser <boomer@ccidnet.com>
.SH "[中文版最新更新]"
.BR 2001/07/19
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
