.TH ID "1" "August 1999" "GNU sh-utils 2.0" FSF
.SH NAME
id \- 显示真实和有效的 UID 和 GID

.SH "总览 (SYNOPSIS)"
.B id
[\fIOPTION\fR]... [\fIUSERNAME\fR]

.SH "描述 (DESCRIPTION)"
.PP
显示 USERNAME 或者 当前 用户 的 信息.
.TP
\fB\-a\fR
忽略, 同 其它 版本 兼容
.TP
\fB\-g\fR, \fB\-\-group\fR
只 显示 组 ID
.TP
\fB\-G\fR, \fB\-\-groups\fR
只 显示 附加组
.TP
\fB\-n\fR, \fB\-\-name\fR
对于 \fB\-ugG\fR 显示 名字 而 不是 数值
.TP
\fB\-r\fR, \fB\-\-real\fR
对于 \fB\-ugG\fR 显示 真实 ID 而 不是 有效 ID
.TP
\fB\-u\fR, \fB\-\-user\fR
只 显示 用户 ID
.TP
\fB\-\-help\fR
显示 帮助 并且 退出
.TP
\fB\-\-version\fR
显示 版本 信息 并且 退出
.PP
如果 没有 OPTION, 显示 指定 指定 的 有用 信息.

.SH "报告错误 (REPORTING BUGS)"
把 错误 报告 给 <bug-sh-utils@gnu.org>.

.SH "参见 (SEE ALSO)"
.B id
的 完整 的 文档 是 以 Texinfo 手册页 维护 的. 如果
.B info
和
.B id
程序 被 正确 的 安装 在 你的 机子 上, 用
.IP
.B info id
.PP
命令 查看 完整 的 手册页.

.SH "版权 (COPYRIGHT)"
版权所有 \(co 1999 自由软件基金会
.br
这一程序是自由软件; 拷贝条件见源文件.
没有任何担保; 甚至没有适合特定目的的隐含的担保.

.SH "[中文版维护人]"
.B 唐友 <tony_ty@263.net>
.SH "[中文版最新更新]"
.BR 2001/9/20
.SH "[中国Linux论坛man手册页翻译计划]"
.BI http://cmpp.linuxforum.net
