.\"
.\"版权所有：Michael Haardt (michael@moria.de), Fri Apr 2 11:32:09 MET DST 1993
.\"中文版版权所有 Alian Yao, www.linuxforum.net 2000
.\"
.\"这是免费文献，可以在Free Software Foundation颁布的GNU General Public License的V2
.\"或更后版本的许可下，重新整理、添加或者修改它们。
.\"
.\" GNU General Public License目标代码和可执行文件的参考文献，以排字系统任何文档输
.\"出形式来解释，包括临时（intermediate）和打印输出。
.\"
.\"发布这个文献，是希望不经授权（甚至是MERCHANTABILITY or FITNESS FOR A 
.\"PARTICULAR PURPOSE的公开授权），就可使用，详见GNU General Public License
.\"
.\"你应该有一份这个手册的GNU General Public License；如果没有，请致函Free Software 
.\"Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\" 
.\"修改时间：Sat Jul 24 16:53:03 1993 by Rik Faith (faith@cs.unc.edu)
.TH INTRO 1 "24 July 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
intro \-介绍用户命令
.SH 描述
这章描述用户命令
.SH 作者
见man页首的作者和版权,不同的页，作者是不同的。

.SH "[中文版维护人]"
.B Alan Yao <Alan_Yao@163.net>
.SH "[中文版最新更新]"
.BR 2000/10/10
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
