.TH "IPCCLEAN" "1" "2003-11-02" "Application" "PostgreSQL Server Applications"
.SH NAME
ipcclean \- 从退出的PostgreSQL服务器中删除共享内存和信号灯

.SH SYNOPSIS
.sp
\fBipcclean\fR
.SH "DESCRIPTION 描述"
.PP
\fBipcclean\fR 删除当前用户拥有的所有共享内存段和信号灯集。 它的目地是在
PostgreSQL 服务器 （\fBpostmaster\fR(1)）崩溃之后进行清理。 请注意的是立
即重起服务器也会清理共享内存和信号灯，所以这条命令实际上用处不大。
.PP
应该只有数据库管理员可以运行这条命令，因为如果在多用户的环境中执行， 它会
导致怪异的行为（也就是说，崩溃）。 如果在服务器运行时执行这条命令， 服务
器分配的共享内存和信号灯将被删除。 这通常会导致该服务器启动的后端服务器的
普遍失败。
.SH "NOTES 注意"
.PP
这个脚本是个\(lqhack\(rq，但是从写成它的这些年来， 没有人提出等效的可移植的解决
方法。因为 \fBpostmaster\fR 现在可以清理自己，所以以后很可能不会继续改进
ipcclean。
.PP
这个脚本对 \fBipcs\fR 工具的输出做了一些假设， 而这些假设可能在不同的操作
系统间是不同的。因此，它可能不能在你的系统上运行。
.SH "译者"
.B Postgresql 中文网站
.B 何伟平 <laser@pgsqldb.org>
