.\" -*- nroff -*-
.TH LSATTR 1 "1999年11月" "E2fsprogs version 1.18"
.SH NAME(名称)
lsattr \- 显示文件在Linux第二扩展文件系统上的特有属性
.SH SYNOPSIS(总览)
.B lsattr
[
.B \-RVadv
]
[
.I files...
]
.SH DESCRIPTION(描述)
.B lsattr
显示文件在Linux第二扩展文件系统上的特有属性
.SH OPTIONS(选项)
.TP
.B \-R
递归地列出目录以及其下内容的属性.
.TP
.B \-V
显示程序版本.
.TP
.B \-a
列出目录中的所有文件,包括以`.'开头的文件的属性.
.TP
.B \-d
以列出其它文件的方式那样列出目录的属性,
而不列出其下的内容.
.TP
.B \-v
显示文件版本.
.SH AUTHOR(作者)
.B lsattr
的作者是Remy Card <card@masi.ibp.fr>,
他是ext2 fs的开发和维护者.
.SH BUGS
没有:-).
.SH AVAILABILITY(怎样获取)
.B lsattr
是e2fsprogs包的一部分,你可以通过
对tsx-11.mit.edu的匿名ftp访问在
/pub/linux/packages/ext2fs下找到它.
.SH SEE ALSO(另见)
.BR chattr (1)

.SH "[中文版维护人]"
.B riser <boomer@ccidnet.com>
.SH "[中文版最新更新]"
.BR 2001/08/08
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
