.TH PASTE "1" "December 1999" "GNU textutils 2.0a" FSF
.SH NAME
paste \- 合并文件各行
.SH "总览 (SYNOPSIS)"
.B ../src/paste
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH "描述 (DESCRIPTION)"
.\" Add any additional description here
.PP
连续 依次 从 各个 文件 FILE 中 读取 一行 然后 合并成 新行,
中间 用 TAB 隔开, 新行 写到 标准输出.
如果 文件 FILE 不存在, 或者 FILE 是 '-', 就从 标准输入 读取 数据.
.TP
\fB\-d\fR, \fB\-\-delimiters\fR=\fILIST\fR
循环使用 LIST 中 的 字符 取代 TAB
.TP
\fB\-s\fR, \fB\-\-serial\fR
一次 粘贴 一个 文件, 而不是 并行 粘贴
.TP
\fB\-\-help\fR
显示 帮助信息, 然后 结束
.TP
\fB\-\-version\fR
显示 版本信息, 然后 结束
.SH "作者 (AUTHOR)"
David M. Ihnat.
.SH "报告 BUGS"
发现的 bug 送往 <bug-textutils@gnu.org>.
.SH "版权 (COPYRIGHT)"
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "另见 (SEE ALSO)"
.B paste
的 完整文档 以 Texinfo 手册 的 格式 维护. 如果 正确 安装了
.B info
和
.B paste
程序, 使用 命令
.IP
.B info paste
.PP
能够 访问到 完整 的 手册.

.SH "[中文版维护人]"
.B 徐明 <xuming@users.sourceforge.net>
.SH "[中文版最新更新]"
.BR 2003/05/13
.SH "《中国Linux论坛man手册页翻译计划》"
.BI http://cmpp.linuxforum.net
