.TH PSFADDTABLE 1 "28 Oct 1997" "控制台工具" "Linux 用户手册"

.SH NAME
psfaddtable \- 添加一个Unicode字符表到控制台字体中

.SH 总览
.B psfaddtable
.I 字体文件 表文件 [输出文件]

.SH 描述
.B Psfaddtable
命令融合了
.I 字体文件
提供的 .psf 格式的控制台字
体和
.I 表文件
提供的Unicode字符表, 生成一个带有嵌入字符表的
字体文件, 并将其写到
.I 输出文件
(如果该文件给出, 否则写到标
准输出). 
.I 字体文件
或者
.I 输出文件
都可以用单个的破折号(\-)取
代以从标准输入读入, 但不能两者同时都是. 如果
.I 字体文件
已经
包含了一个嵌入字符表, 会被忽略. 

.SH 表文件格式
.I Tablefile
文件中各行可以是空白行, 或者是注释行(以
.IR # 
领头), 也可以包含一串十进制数字(缺省情况), 或者包含一串八进制数字
(以
.IR 0  领头), 
或包含一串十六进制数字(以
.IR 0x 
领头). 各行第一个
数字指出所索引字体中的符号位置, 对于256\-字符的字体, 该数在
0到0xff之间, 而对于512\-字符的字体, 该数则处在0到0x1ff之间. 
同一行中随后的任何一个数字都是该特有符号位置的Unicode匹配. 
另外对同一个符号允许有多个行.

.SH "另见"
.BR consolechars (8),
.BR psfgettable (1),
.BR psfstriptable (1).
