.TH PSFGETTABLE 1 "28 Oct 1997" "控制台工具" "Linux 用户手册"

.SH NAME
psfgettable \- 从控制台字体中提取出嵌入的Unicode字符表

.SH 总览
.B psfgettable
.I 字体文件 [输出文件]

.SH 描述
.B psfgettable
命令从一个 .psf 格式的控制台字体中提取出嵌入的
Unicode字符表, 以易读格式输入到一个ASCII文件, 该文件的格式
如同
.BR psfaddtable (1)
所使用的. 若字体文件名是单个破折号(\-), 
则字体从标准输入读取.

.SH "另见"
.BR consolechars (8),
.BR psfaddtable (1),
.BR psfstriptable (1).

