.TH SHOWFONT 1 "28 Oct 1997" "控制台工具" "Linux 用户手册"

.SH NAME
showfont \- 展示当前"显示屏-字体 映射"中的所有字符.

.SH 总览
.B showfont

.SH 描述
.B showfont
利用8-bit控制台模式的
.I Application Charset Map(应用字符集映射)
中一些连续的开关, 以当前字体在屏幕上展示所有的256个或512个字符.

.SH "另见"
.BR consolechars (8).

.SH "[中文版维护人]"
.B 姓名 <email>
.SH "[中文版最新更新]"
.B 2001/02/24
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
