.TH TAC "1" "Decemuber 1999" "GNU textutils 2.0a" FSF
.SH NAME
tac \- 反转显示文件
.SH "总览 (SYNOPSIS)"
.B ../src/tac
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH "描述 (DESCRIPTION)"
.\" Add any additional description here
.PP
把 每个 文件 FILE 显示在 标准输出, 后面 的 行 放在 前面.
如果 没有 指定 文件 FILE 或者 FILE 是 -, 就从 标准输入 读取 数据.
.TP
\fB\-b\fR, \fB\-\-before\fR
把 分隔单元 移到 前面, 而不是 后面
.TP
\fB\-r\fR, \fB\-\-regex\fR
分隔单元 是 正规表达式
.TP
\fB\-s\fR, \fB\-\-separator\fR=\fISTRING\fR
用 STRING 取代 换行符(newline) 作为 分隔单元
.TP
\fB\-\-help\fR
显示 帮助信息, 然后 结束
.TP
\fB\-\-version\fR
显示 版本信息, 然后 结束

.SH "作者 (AUTHOR)"
Jay Lepreau 和 David MacKenzie.

.SH "报告 BUGS"
发现的 bug 送往 <bug-textutils@gnu.org>.

.SH "版权 (COPYRIGHT)"
Copyright \(co 1999 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "另见 (SEE ALSO)"
.B tac
的 完整文档 以 Texinfo 手册 的 格式 维护. 如果 正确 安装了
.B info
和
.B tac
程序, 使用 命令
.IP
.B info tac
.PP
能够 访问到 完整 的 手册.

.SH "[中文版维护人]"
.B 徐明 <xuming@users.sourceforge.net>
.SH "[中文版最新更新]"
.BR 2003/05/13
.SH "《中国Linux论坛man手册页翻译计划》"
.BI http://cmpp.linuxforum.net
