.TH YES "1" "1999年8月" "GNU sh-utils 2.0" FSF
.SH NAME(名称)
yes \- 不断输出一个字符串,直到杀死其为止
.SH SYNOPSIS(总览)
.B yes
[\fIOPTION\fR]... [\fISTRING\fR]...
.SH DESCRIPTION(描述)
.PP
.\" 在这儿添加任何附加的描述信息
.PP
不断输出包括所有指定STRING(s)的一行,或者是`y'.
.TP
\fB\-\-help\fR
显示帮助并退出
.TP
\fB\-\-version\fR
输出版本信息并退出
.SH "REPORTING BUGS"(报告BUGS)
报告bugs,请发到<bug-sh-utils@gnu.org>
.SH "SEE ALSO"(另见)
.B yes
的完整文档以Texinfo手册的形式维护.如果你正确安装了
.B info
和
.B yes
程序,那么命令
.IP
.B info yes
.PP
应该可让你访问到整个手册.
.SH COPYRIGHT
Copyright \(co 1999 Free Software Foundation, Inc.
.br
这是自由软件;参看复制条件的源文件.不承担任何责任;更不用说商业性或针对特定目的的适
用性.

.SH "[中文版维护人]"
.B riser <boomer@ccidnet.com>
.SH "[中文版最新更新]"
.BR 2001/08/08
.SH "《中国linux论坛man手册页翻译计划》:"
.BI http://cmpp.linuxforum.net
