.TH ZLESS 1
.SH NAME
zless \- 用于在显示器上阅读被压缩的文本文件的过滤器

.SH "总览 (SYNOPSIS)"
.B zless
[ name ...  ]

.SH "描述 (DESCRIPTION)"
.I  Zless
是一个文件过滤器, 用于在终端上全屏幕形式查看压缩的或没压缩的文本文件.
它等于把环境变量 PAGER 设置为
.I less,
然后运行 zmore. 但是很多人认为
.I zless
命令很重要, 值得提供.

.SH "另见 (SEE ALSO)"
zmore(1), less(1)

.SH "[中文版维护人]"
.B 徐明 <xuming@users.sourceforge.net>
.SH "[中文版最新更新]"
.BR 2004/02/8
.SH "《中国Linux论坛man手册页翻译计划》"
.BI http://cmpp.linuxforum.net


