.\" 说明：本文件演示 man 文件格式，可供翻译 man pages 及编写 man 相关的程序参考

.TH cmanformat 9 2000.10.6 "RedCandle LinuxForum" " man 格式演示 "

.SH NAME
cmanformat \- 不是命令啦，是个演示文件 :)

.SH "总览 SYNOPSIS"

略

.SH "描述 DESCRIPTION"

cmanformat 是 man pages 格式的演示文件。

由于系统不同会有差异。在 XWindow 下会好些。

.SH ___________________________________
.BR 
.SH 字体演示

.TP

黑 体 字

.B 黑体字黑体字黑体字黑体字黑体字

.TP

黑体和下划线 (或斜体) 交替 (描述函数时非常有用)

.BI "黑体"\fR和\fP下划线 "黑体"\fR和\fP下划线

.TP

黑体和普通体交替 (描述引用时非常有用)

.BR "黑体"\fR和\fP普通体 "黑体"\fR和\fP普通体

.TP

下划线 (或斜体，系统不同会有差异)

.I 下划线下划线下划线下划线下划线

.TP

下划线 (或斜体) 和黑体交替

.IB "下划线 (或斜体) "\fR和\fP黑体 "下划线 (或斜体) "\fR和\fP黑体

.TP

下划线 (或斜体) 和普通体交替

.IR "下划线 (或斜体) "\fR和\fP普通体 "下划线 (或斜体) "\fR和\fP普通体

.TP

普通体和下划线 (或斜体) 交替

.RI "普通体"\fR和\fP下划线 "普通体"\fR和\fP下划线

.TP

小 号 字

.SM 小号字小号字小号字小号字小号字

.TP

小号字和黑体交替

.SB "小号字"\fR和\fP黑体

.SH ___________________________________
.BR
.SH 缩进演示

.I 无缩进

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.I 相对缩进

.P

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.RS

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.RS

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.RS

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.RS

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.RS

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.RE
.RE
.RE
.RE
.RE

.P

.I 悬挂式缩进

.HP

aaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

.P

.I 悬挂标签缩进 1 （不贴标签）

.IP

aaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

.P

.I 悬挂标签缩进 2.1 （贴短标签）

.IP 标签

aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

.P

.I 悬挂标签缩进 2.2 （贴长标签）

.IP 很长的标签

aaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

.P

.I 悬挂标签（和 IP 相同）

.TP

aaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

.SH ___________________________________
.BR
.SH 超级链接 (转换为其他格式文件时有用)

1） .UR http://www.sina.com.cn

.UE

2） .UN "link to sina"

.UR http://www.sina.com.cn

.UE

.UN "link to sina"

.SH ___________________________________
.BR
.P

.SH 杂项宏

.P

.I 在段中空开一定距离 (好象不起作用) :(

.PD
aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

.P

.I 段中的子标题

.SS 子标题

aaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaa

.SH ___________________________________
.BR
.SH 预定义字符串

\*R 注册符号

\*S 改变成缺省字体大小

\*(Tm 商标符号

\*(lq 左双引号

\*(rq 右双引号

.SH ___________________________________
.BR
.SH "返回值 Return Value"

无

.SH "退出状态 Exit Status"

无

.SH "选项 OPTIONS"

无

.SH "参数 ARGUMENTS"

无

.SH "用法 USAGES"

如果你是没有运行过 man cmanformat 就在命令行运行一下。
不过除了这种办法，你也不大可能看到这段介绍。:)

告诉我，你是从什么地方得知本文档的－－选项有：
.br
朋友，家人，报纸，网络，说明书

.SH "文件 FILES"

cmanformat.9

.SH "环境 ENVIRONMENT"

也许会和你的locale 即语言环境设置有关。
再说一遍，如果你正常地看到了这几行字，就完全没有问题了；
但是如果你看不到，那我也不可能在这里给你提出建议。
参见 \fBman\fR(1) 和相关命令 \fBless\fR(1), \fBgroff\fR(1) 的文档

.SH "诊断 DIAGNOSIS"

略

.SH "安全要点 SECURITY ISSUE"

请放心使用

.SH "注意 NOTES"

无

.SH "已知漏洞 KNOWN BUGS"

在字符界面下有些字体无法显示（只能显示普通体和黑体）,
这是中文字库的不足，目前没有办法解决。

.SH "作者 AUTHORS"

.TP

RedCandle

redcandle51@chinaren.com

.SH "参见 SEE ALSO"

man(7), groff(1), less(1)

参与翻译的成员请注意DOCS 目录提供的词汇表，还有以下内容：
man手册中文版的署名的形式为：
（一定要保留原英文作者名字，版权等信息，只要将下面一段复制粘贴到文档最后即可，注意空格）
.SH "[中文版维护人]"
可以将译者信息放在这里，如果译者不想管理自己的“产品”，也可以把信息放在注释中，就像这样
.br
.B .\e" 姓名 <email>
.br
.B RedCandle <email>
.SH "[中文版最新更新]"
.B yyyy.mm.dd
.SH "[中国linux论坛中文手册页翻译计划]:"
.BI http://cmpp.linuxforum.net
