.\" 文件最前面的注释等等请保留不要翻译，不明白其意义的代码也请保留

.TH example 9 cman1.4 "Nov 01,2003"
.\" 注意上面一行中的空格。

.SH NAME
\fBexample\fR \- 在这里插入一句话的简介

.SH "总览 (SYNOPSIS)"
\fBexample\fR [options] arguments

.SH "描述 (DESCRIPTION)"
在这里插入描述

\fBman9\fR 应当是 “内核文档” 但是由于内核文档一般不以 man 形式出现 所以这里借用一下，存放一个翻译好的手册页的框架。正确的位置应当是 \fBman7\fR 即 “杂项” 中。参见 \fIman\fR(1) 中对于各类手册页用途的叙述。

.SH "选项 (OPTIONS)"
在这里插入对选项的说明

.SH "示例 (EXAMPLE)"
在这里插入示例

.SH "版本 (VERSION)"
在这里插入版本，如果有的话

.SH "参见 (SEE ALSO)"
如果在翻译工作之外，还参加了软件包的管理，请参阅下列文档：
.BR nroff(1) ,
.BR groff(1) ,
.BR troff(1) ,
.BR groff(7) ,
.BR man(1) ,
.BR mdoc-samples(7)

.SH BUGS
在这里插入BUGS 的描述，如果有的话

.SH "作者 (AUTHORS)"
作者等信息不需要翻译和变化

.SH "版权 (COPYRIGHT)"
版权信息也不需要翻译和变化

.br
下面六行签名档只需要修改相应内容
.SH "[中文版维护人]"
.B 名字 <电子邮件>
.SH "[中文版最新更新]" 
.B 2001/02/24
.SH "[中国linux论坛中文手册页翻译计划]"
.BI http://cmpp.linuxforum.net

.\" 请在这里以注释形式加入译者的
.\" 名字<电子邮件>
.\" 并加入自己所做工作的概述
