.\"{{{}}}
.\"{{{  Title
.TH MESG 1 "Feb 26, 2001" "" "Linux User's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
mesg \- control write access to your terminal
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B mesg
.RB [ y | n ]
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B Mesg
controls the access to your terminal by others.  It's typically used to
allow or disallow other users to write to your terminal (see \fBwrite\fP(1)).
.\"}}}
.\"{{{  Options
.SH OPTIONS
.IP \fBy\fP
Allow write access to your terminal.
.IP \fBn\fP
Disallow write access to your terminal.
.PP
If no option is given, \fBmesg\fP prints out the current access state of your
terminal.
.PP NOTES
\fBMesg\fP assumes that it's standard input is connected to your
terminal. That also means that if you are logged in multiple times,
you can get/set the mesg status of other sessions by using redirection.
For example "mesg n < /dev/pts/46".
.SH AUTHOR
Miquel van Smoorenburg (miquels@cistron.nl)
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
.BR talk (1),
.BR write (1),
.BR wall (1)
.\"}}}
