.TH ZLESS 1
.SH NAME
zless \- file perusal filter for crt viewing of compressed text
.SH SYNOPSIS
.B zless
[ name ...  ]
.SH DESCRIPTION
.I  Zless
is a filter which allows examination of compressed or plain text files
one screenful at a time on a soft-copy terminal.  It is the equivalent of
setting the environment variable PAGER to 
.I less,
and then running zmore.  However, enough people seem to think that having the
command 
.I zless
available is important to be worth providing it.
.SH "SEE ALSO"
zmore(1), less(1)
